"""
Nginx reload sidecar for IsolateX.
Polls the orchestrator for running instances and writes/removes
per-instance Nginx upstream config files, then reloads Nginx.

Run this as a sidecar in the same container/pod as Nginx, or as a
separate service with access to the Nginx config volume.

Usage:
  python reload-sidecar.py

Env vars:
  ISOLATEX_URL          orchestrator URL (default http://orchestrator:8080)
  ISOLATEX_API_KEY      shared secret
  NGINX_CONF_DIR        where to write instance configs (default /etc/nginx/conf.d/isolatex)
  POLL_INTERVAL         seconds between polls (default 10)
"""
import os
import time
import subprocess
import httpx
from pathlib import Path

ORCHESTRATOR_URL = os.environ.get("ISOLATEX_URL", "http://orchestrator:8080")
API_KEY = os.environ.get("ISOLATEX_API_KEY", "")
CONF_DIR = Path(os.environ.get("NGINX_CONF_DIR", "/etc/nginx/conf.d/isolatex"))
POLL_INTERVAL = int(os.environ.get("POLL_INTERVAL", "10"))

CONF_DIR.mkdir(parents=True, exist_ok=True)


def fetch_instances() -> list[dict]:
    try:
        resp = httpx.get(
            f"{ORCHESTRATOR_URL}/traefik/config",
            headers={"x-api-key": API_KEY},
            timeout=10.0,
        )
        resp.raise_for_status()
        # Reuse the Traefik config endpoint — it lists all running instances
        # with their backend URLs
        data = resp.json()
        services = data.get("http", {}).get("services", {})
        routers = data.get("http", {}).get("routers", {})
        result = []
        for key, router in routers.items():
            host_rule = router.get("rule", "")
            host = host_rule.replace("Host(`", "").replace("`)", "")
            svc = services.get(key, {})
            servers = svc.get("loadBalancer", {}).get("servers", [])
            if servers:
                result.append({"key": key, "host": host, "upstream": servers[0]["url"]})
        return result
    except Exception as e:
        print(f"[sidecar] fetch error: {e}")
        return []


def write_config(instance: dict):
    key = instance["key"]
    host = instance["host"]
    upstream_url = instance["upstream"].replace("http://", "")
    conf = f"""# Auto-generated by IsolateX nginx sidecar — do not edit manually
upstream isolatex_{key} {{
    server {upstream_url};
    keepalive 4;
}}

server {{
    listen 443 ssl;
    server_name {host};

    ssl_certificate     /etc/letsencrypt/live/ctf.osiris.sh/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ctf.osiris.sh/privkey.pem;

    location / {{
        proxy_pass http://isolatex_{key};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        limit_req zone=challenge burst=10 nodelay;
    }}
}}
"""
    path = CONF_DIR / f"{key}.conf"
    path.write_text(conf)


def reload_nginx():
    result = subprocess.run(["nginx", "-s", "reload"], capture_output=True)
    if result.returncode != 0:
        print(f"[sidecar] nginx reload failed: {result.stderr.decode()}")
    else:
        print("[sidecar] nginx reloaded")


def main():
    print(f"[sidecar] starting, polling {ORCHESTRATOR_URL} every {POLL_INTERVAL}s")
    last_keys: set[str] = set()
    while True:
        instances = fetch_instances()
        current_keys = {i["key"] for i in instances}

        changed = False
        for inst in instances:
            write_config(inst)
            if inst["key"] not in last_keys:
                changed = True

        for removed in last_keys - current_keys:
            conf_path = CONF_DIR / f"{removed}.conf"
            if conf_path.exists():
                conf_path.unlink()
                changed = True

        if changed:
            reload_nginx()

        last_keys = current_keys
        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
